travis:
  secure:
    BINSTAR_TOKEN: RehoOkZFwFkQKp3IEGyM1wBolVvNmXX4LmuJ3kXi8CnCzy0xi/zsriROfkxwja8QBNhgGzHWb94YewgvZ66YzcFUAFWF3uf70VhSPm9MKdnyPSVjwfWFeMwDeroGux+Q1E/4QdjaZgAyH0bpOsNfI1s80lgRjMcGcRIClZ+OSPPXO2CJq7RelBC4IR4en4JCnimQFY0sdN5OQB6fIn0/ZwH8ZLKBqZiGCZy3J3bLLUaxKUqK5Dlf/+jR/HCOjZJsHm1V4ow3vd9+M8A6yz1f4+3SmUsKb+hP5IrI5Tx5vUZtzlG3VjO7dIZWV2lhFxDedwOmA/REPslgmGJUJlFEqYXTGvnisPRWAQPPfgbgQlolqNVscYMICBKGDJ8sKZZBZdj42iFYsRztstoJIY4c5XIECNZUA0KrpfCTTWUjTNHvQmB2/FAZxgG9E6xJXM9O6xE4N9yMj5S3g76SUk4Ekl0Z3XFlcCLC1IriDG7qBJ/OQQXBq6ZtYeITn8ljbMz+RJdf7N0Wfe7prbNAOGmSKmpe62/TAOyMysMREA4ZDTVwI0xhHyfYio+egShsF0pUGP55lYJ0gvNHspy5V52p1TbQAISzths7YC1N3wRCWGg3I4c8rcVTfFFipCbIqDSkIGCbVripkqgHUAX3gsnKhPw79PFaVgze4M+P3bXVOIY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
